"""
This type stub file was generated by pyright.
"""

from typing import Optional

crypto_aead_chacha20poly1305_ietf_KEYBYTES: int = ...
crypto_aead_chacha20poly1305_ietf_NSECBYTES: int = ...
crypto_aead_chacha20poly1305_ietf_NPUBBYTES: int = ...
crypto_aead_chacha20poly1305_ietf_ABYTES: int = ...
crypto_aead_chacha20poly1305_ietf_MESSAGEBYTES_MAX: int = ...
_aead_chacha20poly1305_ietf_CRYPTBYTES_MAX = ...
crypto_aead_chacha20poly1305_KEYBYTES: int = ...
crypto_aead_chacha20poly1305_NSECBYTES: int = ...
crypto_aead_chacha20poly1305_NPUBBYTES: int = ...
crypto_aead_chacha20poly1305_ABYTES: int = ...
crypto_aead_chacha20poly1305_MESSAGEBYTES_MAX: int = ...
_aead_chacha20poly1305_CRYPTBYTES_MAX = ...
crypto_aead_xchacha20poly1305_ietf_KEYBYTES: int = ...
crypto_aead_xchacha20poly1305_ietf_NSECBYTES: int = ...
crypto_aead_xchacha20poly1305_ietf_NPUBBYTES: int = ...
crypto_aead_xchacha20poly1305_ietf_ABYTES: int = ...
crypto_aead_xchacha20poly1305_ietf_MESSAGEBYTES_MAX: int = ...
_aead_xchacha20poly1305_ietf_CRYPTBYTES_MAX = ...
crypto_aead_aegis256_KEYBYTES: int = ...
crypto_aead_aegis256_NSECBYTES: int = ...
crypto_aead_aegis256_NPUBBYTES: int = ...
crypto_aead_aegis256_ABYTES: int = ...
crypto_aead_aegis256_MESSAGEBYTES_MAX: int = ...
_aead_aegis256_CRYPTBYTES_MAX = ...
crypto_aead_aegis128l_KEYBYTES: int = ...
crypto_aead_aegis128l_NSECBYTES: int = ...
crypto_aead_aegis128l_NPUBBYTES: int = ...
crypto_aead_aegis128l_ABYTES: int = ...
crypto_aead_aegis128l_MESSAGEBYTES_MAX: int = ...
_aead_aegis256_CRYPTBYTES_MAX = ...
crypto_aead_aes256gcm_KEYBYTES: int = ...
crypto_aead_aes256gcm_NSECBYTES: int = ...
crypto_aead_aes256gcm_NPUBBYTES: int = ...
crypto_aead_aes256gcm_ABYTES: int = ...
crypto_aead_aes256gcm_MESSAGEBYTES_MAX: int = ...
_aead_aegis256_CRYPTBYTES_MAX = ...
def crypto_aead_chacha20poly1305_ietf_encrypt(message: bytes, aad: Optional[bytes], nonce: bytes, key: bytes) -> bytes:
    """
    Encrypt the given ``message`` using the IETF ratified chacha20poly1305
    construction described in RFC7539.

    :param message:
    :type message: bytes
    :param aad:
    :type aad: Optional[bytes]
    :param nonce:
    :type nonce: bytes
    :param key:
    :type key: bytes
    :return: authenticated ciphertext
    :rtype: bytes
    """
    ...

def crypto_aead_chacha20poly1305_ietf_decrypt(ciphertext: bytes, aad: Optional[bytes], nonce: bytes, key: bytes) -> bytes:
    """
    Decrypt the given ``ciphertext`` using the IETF ratified chacha20poly1305
    construction described in RFC7539.

    :param ciphertext:
    :type ciphertext: bytes
    :param aad:
    :type aad: Optional[bytes]
    :param nonce:
    :type nonce: bytes
    :param key:
    :type key: bytes
    :return: message
    :rtype: bytes
    """
    ...

def crypto_aead_chacha20poly1305_encrypt(message: bytes, aad: Optional[bytes], nonce: bytes, key: bytes) -> bytes:
    """
    Encrypt the given ``message`` using the "legacy" construction
    described in draft-agl-tls-chacha20poly1305.

    :param message:
    :type message: bytes
    :param aad:
    :type aad: Optional[bytes]
    :param nonce:
    :type nonce: bytes
    :param key:
    :type key: bytes
    :return: authenticated ciphertext
    :rtype: bytes
    """
    ...

def crypto_aead_chacha20poly1305_decrypt(ciphertext: bytes, aad: Optional[bytes], nonce: bytes, key: bytes) -> bytes:
    """
    Decrypt the given ``ciphertext`` using the "legacy" construction
    described in draft-agl-tls-chacha20poly1305.

    :param ciphertext: authenticated ciphertext
    :type ciphertext: bytes
    :param aad:
    :type aad: Optional[bytes]
    :param nonce:
    :type nonce: bytes
    :param key:
    :type key: bytes
    :return: message
    :rtype: bytes
    """
    ...

def crypto_aead_xchacha20poly1305_ietf_encrypt(message: bytes, aad: Optional[bytes], nonce: bytes, key: bytes) -> bytes:
    """
    Encrypt the given ``message`` using the long-nonces xchacha20poly1305
    construction.

    :param message:
    :type message: bytes
    :param aad:
    :type aad: Optional[bytes]
    :param nonce:
    :type nonce: bytes
    :param key:
    :type key: bytes
    :return: authenticated ciphertext
    :rtype: bytes
    """
    ...

def crypto_aead_xchacha20poly1305_ietf_decrypt(ciphertext: bytes, aad: Optional[bytes], nonce: bytes, key: bytes) -> bytes:
    """
    Decrypt the given ``ciphertext`` using the long-nonces xchacha20poly1305
    construction.

    :param ciphertext: authenticated ciphertext
    :type ciphertext: bytes
    :param aad:
    :type aad: Optional[bytes]
    :param nonce:
    :type nonce: bytes
    :param key:
    :type key: bytes
    :return: message
    :rtype: bytes
    """
    ...

def crypto_aead_aegis256_encrypt(message: bytes, aad: Optional[bytes], nonce: bytes, key: bytes) -> bytes:
    """
    Encrypt the given ``message`` using the AEGIS-256
    construction.

    :param message:
    :type message: bytes
    :param aad:
    :type aad: Optional[bytes]
    :param nonce:
    :type nonce: bytes
    :param key:
    :type key: bytes
    :return: authenticated ciphertext
    :rtype: bytes
    """
    ...

def crypto_aead_aegis256_decrypt(ciphertext: bytes, aad: Optional[bytes], nonce: bytes, key: bytes) -> bytes:
    """
    Decrypt the given ``ciphertext`` using the AEGIS-256
    construction.

    :param ciphertext: authenticated ciphertext
    :type ciphertext: bytes
    :param aad:
    :type aad: Optional[bytes]
    :param nonce:
    :type nonce: bytes
    :param key:
    :type key: bytes
    :return: message
    :rtype: bytes
    """
    ...

def crypto_aead_aegis128l_encrypt(message: bytes, aad: Optional[bytes], nonce: bytes, key: bytes) -> bytes:
    """
    Encrypt the given ``message`` using the AEGIS-128L
    construction.

    :param message:
    :type message: bytes
    :param aad:
    :type aad: Optional[bytes]
    :param nonce:
    :type nonce: bytes
    :param key:
    :type key: bytes
    :return: authenticated ciphertext
    :rtype: bytes
    """
    ...

def crypto_aead_aegis128l_decrypt(ciphertext: bytes, aad: Optional[bytes], nonce: bytes, key: bytes) -> bytes:
    """
    Decrypt the given ``ciphertext`` using the AEGIS-128L
    construction.

    :param ciphertext: authenticated ciphertext
    :type ciphertext: bytes
    :param aad:
    :type aad: Optional[bytes]
    :param nonce:
    :type nonce: bytes
    :param key:
    :type key: bytes
    :return: message
    :rtype: bytes
    """
    ...

def crypto_aead_aes256gcm_encrypt(message: bytes, aad: Optional[bytes], nonce: bytes, key: bytes) -> bytes:
    """
    Encrypt the given ``message`` using the AES-256-GCM
    construction.  Requires the Intel AES-NI extensions,
    or the ARM Crypto extensions.

    :param message:
    :type message: bytes
    :param aad:
    :type aad: Optional[bytes]
    :param nonce:
    :type nonce: bytes
    :param key:
    :type key: bytes
    :return: authenticated ciphertext
    :rtype: bytes
    """
    ...

def crypto_aead_aes256gcm_decrypt(ciphertext: bytes, aad: Optional[bytes], nonce: bytes, key: bytes) -> bytes:
    """
    Decrypt the given ``ciphertext`` using the AES-256-GCM
    construction.  Requires the Intel AES-NI extensions,
    or the ARM Crypto extensions.

    :param ciphertext: authenticated ciphertext
    :type ciphertext: bytes
    :param aad:
    :type aad: Optional[bytes]
    :param nonce:
    :type nonce: bytes
    :param key:
    :type key: bytes
    :return: message
    :rtype: bytes
    """
    ...

