"""
This type stub file was generated by pyright.
"""

from abc import ABCMeta, abstractmethod
from typing import SupportsBytes, Type

class _Encoder(metaclass=ABCMeta):
    @staticmethod
    @abstractmethod
    def encode(data: bytes) -> bytes:
        """Transform raw data to encoded data."""
        ...
    
    @staticmethod
    @abstractmethod
    def decode(data: bytes) -> bytes:
        """Transform encoded data back to raw data.

        Decoding after encoding should be a no-op, i.e. `decode(encode(x)) == x`.
        """
        ...
    


Encoder = Type[_Encoder]
class RawEncoder(_Encoder):
    @staticmethod
    def encode(data: bytes) -> bytes:
        ...
    
    @staticmethod
    def decode(data: bytes) -> bytes:
        ...
    


class HexEncoder(_Encoder):
    @staticmethod
    def encode(data: bytes) -> bytes:
        ...
    
    @staticmethod
    def decode(data: bytes) -> bytes:
        ...
    


class Base16Encoder(_Encoder):
    @staticmethod
    def encode(data: bytes) -> bytes:
        ...
    
    @staticmethod
    def decode(data: bytes) -> bytes:
        ...
    


class Base32Encoder(_Encoder):
    @staticmethod
    def encode(data: bytes) -> bytes:
        ...
    
    @staticmethod
    def decode(data: bytes) -> bytes:
        ...
    


class Base64Encoder(_Encoder):
    @staticmethod
    def encode(data: bytes) -> bytes:
        ...
    
    @staticmethod
    def decode(data: bytes) -> bytes:
        ...
    


class URLSafeBase64Encoder(_Encoder):
    @staticmethod
    def encode(data: bytes) -> bytes:
        ...
    
    @staticmethod
    def decode(data: bytes) -> bytes:
        ...
    


class Encodable:
    def encode(self: SupportsBytes, encoder: Encoder = ...) -> bytes:
        ...
    


